spring.datasource.url=jdbc:postgresql://dpg-d77ur30ule4c73di9pd0-a:5432/placementdb
spring.datasource.username=placementdb_0nhu_user
spring.datasource.password=KR7MIojQSzGlBoyYpaGvjYJj2eZEBNPQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}